### ISSUE TITLE
In app Reviews on version 3, how to check if the user has indeed review

### ISSUE THREAD

**Issue by CDrosos** [jamesmontemagno/StoreReviewPlugin#12]
Is there a way to know if after displaying the review UI that the user indeed used it and make a review?
Or the proper way is for the app consider that the user has made a review the moment we show the UI regardless of his actions?

**Comment by saamerm** [comment]
Hey @CDrosos, on both iOS and Android, so far there is no way to tell whether the user has left a review or pressed the cancel button.
To get around this, developers generally display a dialog before showing the review flow, asking whether or not they would like to review the app.

**Comment by CDrosos** [comment]
Well displaying a dialog does not ensure that he actually review, i guess the current logic is to consider as "not interested to review" if he went that far to see a review UI and did not review in the end

**Comment by saamerm** [comment]
Yes you’re right
