### ISSUE TITLE
[Bug] In app review works exactly once and crashes on other attempts

### ISSUE THREAD

**Issue by maxkoshevoi** [jamesmontemagno/StoreReviewPlugin#15]
## Bug 

Version Number of Plugin: 3.0.0-beta
Device Tested On: Google Pixel 4 XL (android 11), Xiaomi Mi 5 (android 8)
Simulator Tested On: -

### Expected Behavior
I can open in app review popup more then one time

### Actual Behavior
Nothing happens or app crashes

### Steps to reproduce the Behavior
1) Install **beta** version of this app: https://play.google.com/store/apps/details?id=com.whitebox.nuretimetable
2) Go to `Menu` tab
3) Click on `Rate the app`
4) After you'll see in app review popup click outside it (so it closes)
5) Click on `Rate the app` again
6) You won't be able to open in app review popup again no matter what you do (even app reinstall won't help)

### Additional info
Video of the issue: https://photos.app.goo.gl/MoXgRaVmMw3FXnxX6
Source code: https://github.com/maxkoshevoi/NureTimetable/blob/master/NureTimetable/NureTimetable/UI/ViewModels/Info/MenuViewModel.cs#L57
Exception info: [report-2517968357235299999-9b8f9ae9-4252-41b1-b305-72c434be123c.txt](https://github.com/jamesmontemagno/StoreReviewPlugin/files/5542921/report-2517968357235299999-9b8f9ae9-4252-41b1-b305-72c434be123c.txt)

**Comment by saamerm** [comment]
@maxkoshevoi thank you for opening the issue!
Could you please check to see if it is related to [this issue](https://github.com/jamesmontemagno/StoreReviewPlugin/issues/13#issuecomment-720212248)?

**Comment by maxkoshevoi** [comment]
@saamerm hi. Doesn't seem so. I don't use `Xamarin.AndroidX...` packages and using latest version of Xamarin Forms NuGet

**Comment by maxkoshevoi** [comment]
@saamerm sorry, misunderstood the issue. For now in app review is available only in public beta version of my app, so seems like it should work

**Comment by maxkoshevoi** [comment]
Ow, so there is no point of calling this more then once a month? Interesting. Seems like it's impossible (from a practical standpoint) to make this a button. 

https://developer.android.com/guide/playcore/in-app-review#quotas

![image](https://user-images.githubusercontent.com/6609929/99195196-e83abb80-278c-11eb-92ec-65eac2f144d4.png)

But still, calling `RequestReview` shouldn't throw an exception, which it sometimes does now

**Comment by saamerm** [comment]
Yeah certainly, it doesn’t seem to make it a button. Can you try to wait between clicks and see if it still crashes? It seems to be a Task cancellation exception

**Comment by maxkoshevoi** [comment]
Yes, It indeed doesn't crash if I don't click too often.

**Comment by maxkoshevoi** [comment]
I think this issue can be closed then, but could you please mention somewhere (is your article and in readme here) that this functionality can only be used several times a year?

Thanks for your help =)

**Comment by saamerm** [comment]
@maxkoshevoi Sounds great! Btw, check out (this sample)[https://github.com/PatGet/XamarinPlayCoreUpdater] and see if you have the same exception
