### ISSUE TITLE
Testing RequestReview on Android

### ISSUE THREAD

**Issue by JulesMoorhouse** [jamesmontemagno/StoreReviewPlugin#19]
## Additional Feature Request:
I was confused by the Test folder, I assumed for a long time this was for unit tests, not an example. 
—
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 3.0.0-beta
Device Tested On: None
Simulator Tested On: Android Emulator

### Expected Behavior
Seeing the Review dialog appear on Android during testing

### Actual Behavior
Review dialog can not be seen.

### Steps to reproduce the Behavior
I started out copying the code from the plugin as I wanted to do something different on iOS (see my [other issue](https://github.com/jamesmontemagno/StoreReviewPlugin/issues/18)).

But then I used the plug-in directly and have the same issue.

I've not seen the rating dialog or what ever is supposed to shown when you used `RequestReview ` on Android.

I found this [blog post](https://devblogs.microsoft.com/xamarin/android-in-app-reviews/), I've tried `internal app sharing`, but still haven't seen the dialog.

I believe I should be able to easily see the `FakeReviewManager` dialog without too much trouble. But I've never seen that.

Our app have been on Google play for some time.

I don't think it is an issue with ApplicationId, as that not required by the FakeReviewManager anf the Store review page method works fine with the PackageName. Also we don't use Link all.

Any suggestions ?

**Comment by JulesMoorhouse** [comment]
@saamerm and ideas ?

**Comment by Kapusch** [comment]
Quoted from this [blog post](https://devblogs.microsoft.com/xamarin/android-in-app-reviews/#testing) :

> Testing in-app reviews is tricky on Android, just as it is on iOS. There are many limitations to being able to test your app as you can [see here](https://developer.android.com/guide/playcore/in-app-review/test). Regardless of what you try, you won’t be able to see the In-App review UI when built and distributed manually. You have to download the app from the Play Store, in order to see the UI. So, the easiest way to test this is by using Android’s “Internal App Sharing”.

**Comment by JulesMoorhouse** [comment]
I tried the internal app sharing with the FakeReviewManager and still didn’t see the ui.

**Comment by saamerm** [comment]
@JulesMoorhouse thanks for tagging me. 
I wasn't able to do anything tangible through the UI using 'FakeReviewManager' either, and there's no good Android Java documentation out there about how it's supposed to help with testing yet. 

Yes, You will be able to test the real, (non test) Review request in Internal App Sharing! Let me know if that doesn't work for you

**Comment by JulesMoorhouse** [comment]
@saamerm thank you
