### ISSUE TITLE
Compatible Win 8.1 and WP 8.1?

### ISSUE THREAD

**Issue by hadihashem** [jamesmontemagno/StoreReviewPlugin#2]
Hello
Is it compatible on old Win 8.1 and WP 8.1?
Because I get this error message when I use it:
"_This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation._"
Regards

**Comment by jamesmontemagno** [comment]
I only support UWP and above
