### ISSUE TITLE
Question about frequency.

### ISSUE THREAD

**Issue by kaviraj93** [jamesmontemagno/StoreReviewPlugin#21]
Hi,
I know this is not an issue, but a question. I can't find a way to raise a question on GitHub.
Is there a way to check whether users already rated? I don't wanna show the prompt if already rated.
And is there a way to get when last time ignored rating? If ignored I want to wait a week and then show the prompt again.

**Comment by saamerm** [comment]
As far as I know from what I have read, there is no way. 

Xamarin is the closest to native development, so whenever you are in doubt, you can just google if a feature is possible in Swift on iOS and Java in Android. If it is possible there, then it is possible on Xamarin

**Comment by kaviraj93** [comment]
Thank you very much @saamerm and @jamesmontemagno respond to my question.
I really appreciate it.
