### ISSUE TITLE
RequestReview not working on Android

### ISSUE THREAD

**Issue by gogolon** [jamesmontemagno/StoreReviewPlugin#22]
## Bug 

Version Number of Plugin: 2.0.0.5
Device Tested On: Xiaomi Mi A1 (Android 9)
Simulator Tested On: None

### Expected Behavior
Popup showing

### Actual Behavior
Popup not showing

### Steps to reproduce the Behavior
Call
`await Plugin.StoreReview.CrossStoreReview.Current.RequestReview(false);`

### Description
Hello,
I uploaded my app to Play Store, downloaded it from there and the in-app review popup won't show. The problem does not occur on iOS, where the plugin works correctly. On Android nothing happens after calling the RequestReview function. I plugged the device and watched its output in Android Studio, but haven't found anything related.
If it's a known issue that has been already fixed in the 3.1.0 version of the plugin, please let me know.

**Comment by saamerm** [comment]
Did you test it in the "Internal App Sharing" method of Android?

Also, did you try to take a look at this thread? https://github.com/jamesmontemagno/StoreReviewPlugin/issues/13

**Comment by saamerm** [comment]
@gogolon ^

**Comment by gogolon** [comment]
@saamerm I have just tried and it works on Internal App Sharing. So, if I understand well, this is a bug in play core that we can't do anything with?

**Comment by saamerm** [comment]
Yes it could be a bug, or it could just be that Android won't allow you to review in app from that play store account.

Could you try to download from a different android device using a different play store account?

**Comment by gogolon** [comment]
I'll try that.

**Comment by Sgt-Hashtag** [comment]
Its the same for me. I'm also getting not Implemented exception in one scenario. Cant figure out tht as well.

**Comment by saamerm** [comment]
@Sgt-Hashtag your issue is different. You are getting a exception/crash because it sounds like you have set your linker behavior but you haven't added & configured the proguard file correctly as stated in the instructions.

**Comment by Sgt-Hashtag** [comment]
I have . i saw that video of your and followed the exact steps

**Comment by gogolon** [comment]
I'm back. I've checked the publicly available version of the app with another device and a different Google account. Unfortunately, the popup did not show up.

**Comment by queequac** [comment]
Might be helpful if the `StoreReviewImplementation` class would allow to check the result of `RequestReviewFlow` only, without calling `LaunchReviewFlow` on success.
If the result is not successfull, I'd rather prefer not to show the rate-button in my app at all. :)

**Comment by saamerm** [comment]
@gogolon if it shows up on Internal App Sharing then there’s nothing else you can do. As I shared in the closed issues as well, there are some known issues in the native play core package that are unresolved that are faced by Java/kotlin Devs as well.

**Comment by saamerm** [comment]
@Sgt-Hashtag i think you messaged me on Twitter that you were able to figure it out. What was your issue?

**Comment by upsilondynamics** [comment]
Also not working; it does nothing. Any idea?

![image](https://user-images.githubusercontent.com/43655307/115773118-ed281a80-a37d-11eb-8d4d-5e4cd46cb305.png)

**Comment by saamerm** [comment]
Hey @upsilondynamics !
- [ ] Did you test it in the "Internal App Sharing" method of Android?
- [ ] Also, did you try to take a look at this thread? #13
- [ ] Could you try to download from a different android device using a different play store account?

**Comment by Sgt-Hashtag** [comment]
@gogolon Hey internal app sharing method works for me it shows proper pop up with review capability in android. I have not tested IOS but should work just fine

**Comment by gogolon** [comment]
> @gogolon Hey internal app sharing method works for me it shows proper pop up with review capability in android. I have not tested IOS but should work just fine

Thanks for replying. I'm aware that it works on internal app sharing. It's not a good long-term workaround though.

**Comment by saamerm** [comment]
@gogolon that's a limitation of the Google's native play core library functionality.
This is the exact functionality when creating android apps on Java/Kotlin as well

**Comment by saamerm** [comment]
Also I just noticed that your version number is < v3, the in app review functionality was not implemented in that nuget

**Comment by saamerm** [comment]
@gogolon is this still an issue?

**Comment by gogolon** [comment]
According to you it's not related to this nugget, so I'm closing it now. Sorry for not doing it before.

**Comment by petermirmo** [comment]
I am still having this issue. Was anyone able to fix it?
