### ISSUE TITLE
Version info missing

### ISSUE THREAD

**Issue by queequac** [jamesmontemagno/StoreReviewPlugin#23]
The library does not reflect its current version.
Along with open source licenses and other legal stuff I do provide the version info of my dependencies.
Unfortuantely The StoreReview Plugin is always a 1.0, so I have to hardcode the version and must not forget to update it once I update the package in the future.

## Bug 

Version Number of Plugin: 3.1.0

### Expected Behavior
Checking for the assembly's version returns the actual version of the plugin.

### Actual Behavior
Always version 1.0.0.0

## Feature Request:
Would be happy to see the version info in the assembly which is aligned with the nuget version.

**Comment by saamerm** [comment]
What code change will need to be made in the library? Do you want to add a pull request?

**Comment by queequac** [comment]
Most easy solution would be adding
```
[assembly: AssemblyVersion("3.1.0.0")]
[assembly: AssemblyFileVersion("3.1.0.0")]
```
to your [CrossStoreReview.shared.cs](https://github.com/jamesmontemagno/StoreReviewPlugin/blob/master/src/StoreReview.Plugin/CrossStoreReview.shared.cs) file, or by adding a new AssemblyInfo.cs with these attributes.

But a PR won't make sense here, since you'd have to update these attributes with every nuget release anyway, otherwise the version is already outdated again with the next update.

The more elegant solution would be to enhance your build pipeline in a way it sets the version accordingly when creating the nuget package. But I am not an expert on that one. Maybe [this](https://saebamini.com/how-to-version-your-net-nuget-packages-libraries-and-assemblies-azure-yaml-pipelines-example-using-net-core-cli/) helps?

**Comment by jamesmontemagno** [comment]
I think you would read the version number of the nuget?

I could probably pass in more info into the pack command...

**Comment by jamesmontemagno** [comment]
give 3.2.0-beta a try and let me know if it has what you need

**Comment by queequac** [comment]
@jamesmontemagno That was exactly what I was asking for. Thanks!

**Comment by shivraj251** [comment]
How to detect which click event is fired on submit or cancel?

**Comment by saamerm** [comment]
@queequac close issue?
