### ISSUE TITLE
Issue if user tries to Review for the second time.

### ISSUE THREAD

**Issue by iamchandanys** [jamesmontemagno/StoreReviewPlugin#25]
## Bug 

We have the **Rate Us** button in our App and we are calling the below line in that method.

`await CrossStoreReview.Current.RequestReview(false);`

So now the issue is, after giving the Review, if the user clicks on the Rate Us button again, it won't show anything. So the user might think it's the bug.

Version Number of Plugin: 3.1.0
Tested On: Android & iOS.

### Expected Behavior

Once the user gives the review and if they try to give again, at least it needs to show some message like that they have already given Review or at least it needs to redirect to the Play Store or App Store just to make the user knows that they have already given the Review.

### Actual Behavior

If the user clicks on the Rate Us button for the second time, it won't show anything.

### Steps to reproduce the Behavior

Try to give a review for the Second time.

**Comment by saamerm** [comment]
Ah yes! That would have been neat. Unfortunately there's no public api available that can help with that. 
For your feature, you can keep a counter of when the user taps the first time, display the in app review. And for subsequent times, you can perhaps take them to the App Store

**Comment by jamesmontemagno** [comment]
Yup, you shouldn't have a Rate Us button with this feature it is meant for more of a pop up after usage. However if you do, do what @saamerm said.... HOWEVER technically it isn't guaranteed to even come up on iOS even if you call it. Just how it works.

**Comment by iamchandanys** [comment]
@saamerm @jamesmontemagno Got it. Thanks for the respose.
Let me implement as @saamerm suggested.

**Comment by moonios5** [comment]
@jamesmontemagno @saamerm  how we know that review added successfully ?

**Comment by saamerm** [comment]
@moonios5 theres no public api available from iOS or Android that allows us to know if a review was added successfully by the user
