### ISSUE TITLE
Android InAppReview Not Popping Up

### ISSUE THREAD

**Issue by marceloarchiza** [jamesmontemagno/StoreReviewPlugin#26]
## Bug 

Version Number of Plugin: 3.1.0 and 3.2.0-beta
Device Tested On: Samsung S10 (Android 11)

### Expected Behavior
Android In App Review pops up when calling `await CrossStoreReview.Current.RequestReview(false);`
### Actual Behavior
I am not being able to make this work. Android In App Review is not popping up.
### Issue Info
1. Xamarin Essentials is setup correctly. I am calling the correct method and I added a pop up just to show that we are hitting that line:
https://user-images.githubusercontent.com/38107971/125111047-a4415180-e0a2-11eb-98d8-735d8bc8d150.mov

2. This is how I created the internal Test. Is there any specific configuration needed? Or is this enough?
Part 1:
https://user-images.githubusercontent.com/38107971/125111233-e4083900-e0a2-11eb-8b84-4260bf175935.mov
Part 2:
https://user-images.githubusercontent.com/38107971/125111244-e79bc000-e0a2-11eb-99e1-0f7e9f0222b5.mov

3. The following video shows the app store and app behavior on an actual device. The `RequestReview` line is being hit, since the pop up show up:
https://user-images.githubusercontent.com/38107971/125114533-51b66400-e0a7-11eb-92dd-268be42c6a7d.mp4

4. Logs using the following commands:
adb shell
logcat | grep com.marcetown.myapp
[logcat2.docx](https://github.com/jamesmontemagno/StoreReviewPlugin/files/6792977/logcat2.docx)

5. Also, I am not sure if this is relevant, but no code shrinker is being used:
![Screen Shot 2021-07-09 at 10 39 48 AM](https://user-images.githubusercontent.com/38107971/125111044-a3102480-e0a2-11eb-8443-6a08c04e8e26.png)

## Request:
I don't believe this is an actual bug on this library, I just need some help to fix this issue. I followed the suggestions on the other post, but I was not able to fix it. Here is a couple things I tried:
* I tried different accounts.
* Neither accounts reviewed the app yet.

**Comment by antoine-hebert** [comment]
Did you test on a device running Android 10 vs Android 11 ? We are experiencing the same behavior on devices running Android 11.

**Comment by saamerm** [comment]
Guys could you try to download this game and win the game once to see the popup on your android 11?

https://play.google.com/store/apps/details?id=com.tfp.numberbomb

The app uses v3.1 of this package, with target SDK version 30 and target framework v11.0

Most likely you have not read the README completely (I know it's boring) are not using Internal App Sharing to test or you have not setup the pro guard correctly

**Comment by saamerm** [comment]
@marceloarchiza

**Comment by saamerm** [comment]
Please use a [pastebin for your logcat](https://pastebin.com/r3Hpdd2d) (I had to upload your file to Google Drive to open the file)
Also, I noticed in the logs you got this error `Unexpected response code 404 for https://play-fe.googleapis.com/fdfe/allowInAppReview?doc=com.marcetown.myapp`, and I haven't seen anyone else get a similar error

**Comment by marceloarchiza** [comment]
@saamerm I tried your Numberbomb app on Android 11 and it worked as expected. Although I did read the entire read me file multiple times and I am using Internal App Sharing, I assumed I did not need to create the proguard file, since I have no code shrinker and "Link SDK assemblies only".

My bad for sending a docx, first time submitting a large error like that haha Thank you so much for finding this 404 error. Here are the errors I am getting:
```
07-09 10:36:19.834  8532 11374 I Finsky  : [27174] fki.<init>(18): com.marcetown.myapp is installed but certificate mismatch
07-09 10:36:19.962  8532 11214 E Volley  : [27115] doi.a: Unexpected response code 404 for https://play-fe.googleapis.com/fdfe/allowInAppReview?doc=com.marcetown.myapp
```
I believe I am getting this certificate mismatch error due to the way I uploaded the app on the AppStore. I will be testing this directly in prod. I am closing this issue. Thanks for your help!

**Comment by saamerm** [comment]
Yes @marceloarchiza, it's not about the code shrinking, it's the 'Link SDK assemblies only' that requires the pro guard file

**Comment by marceloarchiza** [comment]
Just an update, this was because I was not using internal app testing, but internal test. I had no idea they were different. I got it to work. Thank you again @saamerm!!! Arif and Suchita said hi! Again, thanks for the great work and for your positive impact on MSA even after you left Charter! You are the best!

**Comment by jamesmontemagno** [comment]
🎉🎉🎉🎉

**Comment by boskovaskovic** [comment]
Try to clear the cache of your app.

**Comment by vupq-hnl** [comment]
- [RNKA-508](https://fullswing.atlassian.net/browse/RNKA-508): [Subscription] Apple/Google ID Conflict Error Handling
- [RNKA-505](https://fullswing.atlassian.net/browse/RNKA-505): Remove action tab on spray details
- [RNKA-530](https://fullswing.atlassian.net/browse/RNKA-530): [Account Settings - Units of Measurement] The settings are not saved to the account, only stored on the device
- [RNKA-442](https://fullswing.atlassian.net/browse/RNKA-442): [Live Session - Field] [Tablet] When starting a session, the field screen freezes.
