### ISSUE TITLE
button disabled

### ISSUE THREAD

**Issue by domdp16** [jamesmontemagno/StoreReviewPlugin#3]
Hi, 
I'm using the plugin and invoke the method in this way:

StoreReviewImplementation storeReview = new StoreReviewImplementation();
storeReview.RequestReview();

I saw the popup, choose the stars, but the button "send" continues to be disabled.
why? thanks a lot for the support.

**Comment by jamesmontemagno** [comment]
This is controlled by apple, I just call the api... maybe because your app is not from the app store.
