### ISSUE TITLE
Project with a minimum UWP version of 16299 throws System.NotImplementedException

### ISSUE THREAD

**Issue by BurkusCat** [jamesmontemagno/StoreReviewPlugin#35]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 
On a project with Min uwp version 16299 and target 19041, if you upgrade to StoreReviewPlugin 3.3.0, the app will crash on UWP.

I think this change may be the issue?
![image](https://user-images.githubusercontent.com/7528322/156933270-93b71e30-229b-40e7-a497-6e7ae21182c1.png)
https://github.com/jamesmontemagno/StoreReviewPlugin/commit/2f917ac00be6e602f9890e92ce15a841e9c4af93#diff-33df5eebecd5b6a4d99b60af7f0e6ad462d1e5d89106b33c07ee774d45c032a0

Version Number of Plugin: 3.3.0
Device Tested On: Windows 10 19044

### Expected Behavior
Plugin supports older minimum versions of Windows

### Actual Behavior
Plugin throws an exception on startup.
![image](https://user-images.githubusercontent.com/7528322/156933361-61c079bf-7af6-4ee3-bde9-1097e4d45fde.png)

The issue is fixed if you raise the minimum version of the app up to 19041.

### Steps to reproduce the Behavior
1. Create a project with Min uwp version 16299 and target 19041
2. Use StoreReviewPlugin 3.3.0

**Comment by jamesmontemagno** [comment]
I now build with VS 2022 and only 19041 is there, however as long as your target is set to 19041 it should work just fine...

![image](https://user-images.githubusercontent.com/1676321/157135579-b87bc07d-855a-43c9-ae30-59de658002f8.png)


This is what my app My Stream Timer does and it work for my in app billing plugin where I do the same thing... hmmmm.


Can you double check your nugets file i obj/project.assets.json

you shoudl see something in there for Plugin.StoreReviewPlugin... can you copy and paste that in here

**Comment by jamesmontemagno** [comment]
Oh hmmm maybe i need to set -> `<TargetPlatformMinVersion>10.0.16299.0</TargetPlatformMinVersion>` let me see

**Comment by jamesmontemagno** [comment]
I sill push out 3.3.1-beta if you can try that.

**Comment by BurkusCat** [comment]
Hi James, 3.3.1-beta seems to work well for me, thank you! :)

**Comment by jamesmontemagno** [comment]
awesome!! yay! I will push this out ;)
