### ISSUE TITLE
App freezes after review sent

### ISSUE THREAD

**Issue by s153625** [jamesmontemagno/StoreReviewPlugin#36]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 3.3.0
Device Tested On: Many iOS 14+ devices (iPhone 12 pro, iPad pro (2. generation), 

### Expected Behavior
App continues to run after review
### Actual Behavior
App freezes
### Steps to reproduce the Behavior
1. Use StoreReviewPlugin 3.3.0
2. Submit review with user 
Xamarin forms version: 5.0.0.2291
Xamarin.ios: 152.0.17
## Feature Request:
It seems that the active window is not set correctly. The issue only occurs for iOS 14+ with the SKStoreReviewController.RequestReview that requires a windowScene.

**Comment by jamesmontemagno** [comment]
And also a source code example.

**Comment by saamerm** [comment]
Thanks for the video @s153625 
The good thing is that it happens only after they have submitted an actual review, so they won't see the popup again
I will try to look into this, it is going to be difficult to try to replicate this in production

**Comment by jamesmontemagno** [comment]
Should we remove the code that uses the new stuff? I mean it worked before without it??....

**Comment by saamerm** [comment]
@jamesmontemagno we dont have access to his code, and this is the only report we have received out of >1000 downloads of the package

**Comment by s153625** [comment]
@saamerm Thanks! And yeah its quite difficult to test directly in production
@jamesmontemagno I don't think that it's the latest changes either as this has a problematic for a while

**Comment by saamerm** [comment]
@s153625 could you isolate the code used until code for RequestReview?

**Comment by saamerm** [comment]
@s153625 you could create a secret button to launch the review, so that if a user taps on an image 11 times, it shows the review popup. And you won't need to upload to production, just beta/internal app sharing
