### ISSUE TITLE
App review popup not showing on Android

### ISSUE THREAD

**Issue by dinonovak** [jamesmontemagno/StoreReviewPlugin#37]
Samsung Galaxy A03s
- Android 11
Redmi 9A
- MIUI 12.0,18 / Android 10

Exactly the same behaviour on both phones (using void RequestReview();):
- App is installed using Internal App Sharing - all works review popup shows up
- App deleted and the installed regularly from Google Play Store (exactly same build/binary as in Internal App Sharing) - popup does not show up at all

Switching back to internal app sharing, all works again ?!

Any ideas why it is happening?

**Comment by saamerm** [comment]
Are you logged in to the Google play store using the same account as your android developer account? @dinonovak

**Comment by saamerm** [comment]
Do you want me to test it for you since I am not logged in with the same account as the developer account?

**Comment by dinonovak** [comment]
> Do you want me to test it for you since I am not logged in with the same account as the developer account?

@saamerm send you a DM via mail

**Comment by saamerm** [comment]
![image](https://user-images.githubusercontent.com/8262287/159987288-da4d2e7d-9c93-48f6-aac7-c40fb3d011da.jpeg)
The app is a little unresponsive and the navigation is wonky. But yes I was able to see the review popup @dinonovak

**Comment by dinonovak** [comment]
thanx!

**Comment by saamerm** [comment]
@dinonovak did you want to close this issue?
