### ISSUE TITLE
MAUI support

### ISSUE THREAD

**Issue by pwisk** [jamesmontemagno/StoreReviewPlugin#39]
Will the plugin have MAUI support soon? This is a very useful plugin. Before converting to MAUI, it was on my list to use as a certain item. I tested the code for Windows. I have a problem with libraries for Android.

Version 4.0.0-beta cannot be installed. Has references to Microsoft.Maui.Dependencies 6.0.400 -> Xamarin.AndroidX.Browser (> = 1.4.0.1)
  DebtCollectorMaui -> Plugin.StoreReview 4.0.0-beta -> Xamarin.Essentials 1.7.1 -> Xamarin.AndroidX.Browser (> = 1.3.0.5 && <1.4.0)

**Comment by saamerm** [comment]
There’s a ‘dotnet’ branch. Can you try to down load this library and add it manually to test?

**Comment by saamerm** [comment]
@pwisk

**Comment by jamesmontemagno** [comment]
Shipping today, version 5.0
