### ISSUE TITLE
RequestReview(false) - No pop up on iOS

### ISSUE THREAD

**Issue by viraj-pratapwant-persona** [jamesmontemagno/StoreReviewPlugin#40]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 3.3.1
Device Tested On: iPhone 11 Pro (iOS 15.5)
Simulator Tested On: N/A

### Expected Behavior
RequestReview(false) should show the rating pop up after the app has been pushed live to App Store. This works fine on Android.
### Actual Behavior
No rating pop is seen on iOS when RequestReview(false) is called. However, in debug i.e. on Simulator & on phone, I am able to see the rating pop up.
### Steps to reproduce the Behavior
await CrossStoreReview.Current.RequestReview(false);

## Feature Request:
Please fill in what you would like

**Comment by saamerm** [comment]
How can I replicate this issue? Is this Apple production? When you tested it on the iOS simulator, were you able to see the pop-up?

**Comment by viraj-pratapwant-persona** [comment]
Yes, the pop was shown on the simulator and device while debugging. The same code has gone live (i.e. to the Apple Store/ Apple production) but no pop up there. Hope this was helpful. Perhaps if you have an app that is already in production with this plugin with version 3.3.1, and download on a phone that has iOS 15.x

**Comment by saamerm** [comment]
It’s because you have either already rated it with your Apple ID, or you have uploaded the app using your Apple ID. I would recommend using a different device logged into someone else’s Apple ID to test it out in production

**Comment by viraj-pratapwant-persona** [comment]
Thank you for your prompt responses. I see. I will try with a different device and Apple ID. A question, does this happen for the other review mechanisms such as OpenStoreReviewPage(string appId) as well? Or will that be shown always?

**Comment by saamerm** [comment]
From my knowledge, that function will actually open another app, leaving your current app. So no that behavior does not happen with that function. 
People prefer to use this RequestReview function instead because in this way users can remain within your app

**Comment by saamerm** [comment]
You might want to read up about the underlying API in iOS 
https://developer.apple.com/documentation/storekit/requesting_app_store_reviews
as you know, Xamarin essentially uses the native API‘s in order to perform its functionalities. 

There’s a number of different reasons why your review may not be visible, and that website explains what they may be
