### ISSUE TITLE
Review Popup not showing on Mac Catalyst for MAUI

### ISSUE THREAD

**Issue by saamerm** [jamesmontemagno/StoreReviewPlugin#41]
## Bug 

Version Number of Plugin: v5.0 Beta
Device Tested On: Mac Catalyst app on MacBook Pro 2021 M1
Simulator Tested On: "My Mac"

The Plugin work for iOS apps. But the Review Popup is not showing on Mac Catalyst apps made in MAUI. Running the code doesn't do anything currently (nothing in the Application Output either)

### Possible Reason

As you can see here, Apple has introduced a new function to work for Mac Catalyst : https://developer.apple.com/documentation/storekit/skstorereviewcontroller/3566727-requestreview

We are not using that, which may be the reason the popup doesn't show up
https://github.com/jamesmontemagno/StoreReviewPlugin/blob/52beef6db918dc4eff5ef1ef8748e99ffc63d175/src/StoreReview.Plugin/StoreReviewImplementation.apple.cs#L98

### Expected Behavior

Review popup displays

### Actual Behavior

No review popup is displaying

### Steps to reproduce the Behavior

- Just add the v5.0 pre-release Nuget package and add the code needed for the popup to display on a button click
- Build the iOS app and see it working on clicking that button
- Build the Mac Catalyst app, and the review doesn't display on button click

**Comment by saamerm** [comment]
Unlike I used to before, I'm not able to build the solution when I add the plugin as a project to debug with MAUI. So I wasn't able to make the change and test

**Comment by Stratosf** [comment]
I would love to have this plugin on MAUI

**Comment by jamesmontemagno** [comment]
Should be good in Give https://www.nuget.org/packages/Plugin.StoreReview/7.0.0-beta a try
