### ISSUE TITLE
RequestReview issue

### ISSUE THREAD

**Issue by anherukun** [jamesmontemagno/StoreReviewPlugin#45]
Hi, I have a question about this plugin, I'm using .net maui and my app it's already published in Google PlayStore, but when i'm trying to use this plugin:

 `await CrossStoreReview.Current.RequestReview(false);`

It dosn't show the review page. 

Version Number of Plugin: 5.0.1
Device Tested On: HUAWEI Y7 (ANDROID 8)
Simulator Tested On: ANDROID 11

**Comment by Kapusch** [comment]
Hi @anherukun , in debug mode, did you try to run instead
`await CrossStoreReview.Current.RequestReview(true);`

**Comment by Kapusch** [comment]
Also, you should rephrase your title as this is not reflecting your actual issue

**Comment by Soap-141** [comment]
I'm having the same issue, it doesn't work on Android with internal sharing in Google Play.

**Comment by Soap-141** [comment]
Finally found the issue! We can't use G-Suite accounts to review the application.

**Comment by Symbai** [comment]
I'm having the same problem where it doesn't show up on both, ios and android (MAUI) but only when published in app store. When testing it in ios simulator for example it immediately shows up.

As for iOS I read that its up to the system to show it or not. But as I said it also happens on Android. I'm using the code below:

```C#
#if ANDROID
        await Plugin.StoreReview.CrossStoreReview.Current.RequestReview(true);
#endif
#if IOS
        if (UIDevice.CurrentDevice.CheckSystemVersion(10, 3))
        {
            SKStoreReviewController.RequestReview();
        }
#endif
```
