### ISSUE TITLE
Conflict with Xamarin.Google.Android.Play.Core

### ISSUE THREAD

**Issue by pulmuone** [jamesmontemagno/StoreReviewPlugin#46]
Error...

![image](https://github.com/jamesmontemagno/StoreReviewPlugin/assets/42885949/7bab8009-5ec0-4dbe-9e8d-c305cb1e6311)

**Comment by saamerm** [comment]
@pulmuone i can’t see the error. Could you please share the actual code of the error?

**Comment by pulmuone** [comment]
> @pulmuone i can’t see the error. Could you please share the actual code of the error as a text?

Conflict Sample Source :  Build Error
https://github.com/pulmuone/AppUpdateManagerTest

**Comment by pulmuone** [comment]
@saamerm 

Conflict Sample Source : Build Error
https://github.com/pulmuone/AppUpdateManagerTest

**Comment by jamesmontemagno** [comment]
Oh, i see yes, tehre is an official package now :) i will update to that

**Comment by mina5500** [comment]
@jamesmontemagno 
Is there any existing package for in-app update same as in-app review ? Or any plan to develop new nuget pacakge for in-app update?

**Comment by saamerm** [comment]
@mina5500 theres no way to do in app updates on iOS, so there's likely no plan. You can use the android specific nuget package to implement it in your app

**Comment by pulmuone** [comment]
> 

Hi, ios app auto-update 
https://github.com/pulmuone/AppUpdateManagerTest

ios project : AppDelegate.cs -> WillEnterForeground

**Comment by pulmuone** [comment]
> @jamesmontemagno Hi James ... big fan 😊🤩 Is there any existing package for in-app update same as in-app review ? Or any plan to develop new nuget pacakge for in-app update? (xamarin forms)

Hi, ios app auto-update
https://github.com/pulmuone/AppUpdateManagerTest

ios project : AppDelegate.cs -> WillEnterForeground

**Comment by pulmuone** [comment]
>  @mina5500 

Hi, ios app auto-update
https://github.com/pulmuone/AppUpdateManagerTest

ios project : AppDelegate.cs -> WillEnterForeground
