### ISSUE TITLE
Support Huawei AppGallery for Reviews

### ISSUE THREAD

**Issue by JarJarBinkz** [jamesmontemagno/StoreReviewPlugin#48]
Please add support for the Android Huawei AppGallery store.

So that these Android users can also give a rating.

Thanks a lot

**Comment by saamerm** [comment]
It seems like we would just need to create a PR with these changes
If the `PackageManager.GetInstallerPackageName()` returns "com.huawei.appmarket" as shown here, https://stackoverflow.com/questions/68667149/detecting-if-application-is-installed-from-huawei-appgallery
then we just need to pass this as the intent
```
val intent = Intent("com.huawei.appmarket.intent.action.guidecomment")
intent.setPackage("com.huawei.appmarket")
activityContext.startActivityForResult(intent, inAppReviewResultCode)
```
as shown here https://stackoverflow.com/questions/66990732/there-is-an-equivalent-of-in-app-review-for-huawei-services
