### ISSUE TITLE
User not prompted for review on MAUI WinUI app

### ISSUE THREAD

**Issue by BurkusCat** [jamesmontemagno/StoreReviewPlugin#49]
## Bug 

Version Number of Plugin: 6.0.0
Device Tested On: Windows 11 22H2
Simulator Tested On: N/A

### Expected Behavior
The user is prompted to review the app

### Actual Behavior
In Debug and Release mode (and when downloaded from the store), no review dialog shows.

### Steps to reproduce the Behavior
``` csharp
#if DEBUG
        await storeReview.RequestReview(true);
#else
        await storeReview.RequestReview(false);
#endif
```

**Comment by jamesmontemagno** [comment]
Hmmmm... 

Looks like they have improved the code a bit, I will give it an update: https://learn.microsoft.com/en-us/windows/uwp/monetize/request-ratings-and-reviews#show-a-rating-and-review-dialog-in-your-app

**Comment by BlueRaja** [comment]
Any update on this? Xamarin support ends next week, so everyone is being forced to update to MAUI. Is this plugin dead?

**Comment by jamesmontemagno** [comment]
can you try 6.1.0-beta. i re-implemented it

**Comment by BurkusCat** [comment]
Thanks @jamesmontemagno for writing a new implementation

Immediately after updating the package, and trying it with my app I get this error:
```
Exception thrown: 'System.Runtime.InteropServices.COMException' in WinRT.Runtime.dll
WinRT information: This function must be called from a UI thread
```

Running it on the UI thread using either of the below options does not resolve the issue:
``` csharp
        await MainThread.InvokeOnMainThreadAsync(async () => await storeReview.RequestReview(true));
        MainThread.BeginInvokeOnMainThread(() => storeReview.RequestReview(true));
```

The review logic is being called from a service that decides when to prompt the user (as opposed to being activated on a button press).

**Comment by jamesmontemagno** [comment]
Hmmm it must be invoked on the UI Thread that is for sure.


These are the 2 lines of code that you must call from Windows, try to conditionally compile them and invoke with the dispatcher:

```csharp
  var context = StoreContext.GetDefault();
 var result = await context.RequestRateAndReviewAppAsync();
```

**Comment by jamesmontemagno** [comment]
See: https://learn.microsoft.com/en-us/uwp/api/windows.services.store.storecontext.requestrateandreviewappasync?view=winrt-22621 it "should jus work"

I wonder if I have to do 👍 
```
var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(windowObject);
// Initialize the dialog using wrapper funcion for IInitializeWithWindow
WinRT.Interop.InitializeWithWindow.Initialize(context, hwnd); 
```

**Comment by jamesmontemagno** [comment]
Alright in 6.1.1-beta try this:

```csharp
#if WINDOWS  
var hwnd = ((MauiWinUIWindow)App.Current.Windows[0].Handler.PlatformView).WindowHandle;  
StoreReviewImplementation.WindowObject = hwnd;
#endif  
```

then call it on UI thread

**Comment by BurkusCat** [comment]
1. This didn't work ❌:

``` csharp
#if WINDOWS
        Application.Current.MainPage.Dispatcher.Dispatch(async () =>
        {
            var context = StoreContext.GetDefault();
            var result = await context.RequestRateAndReviewAppAsync();
        });
#endif
```

2. Works with window handle ✅:
``` csharp
#if WINDOWS
        Application.Current.MainPage.Dispatcher.Dispatch(async () =>
        {
            var context = StoreContext.GetDefault();

            var hwnd = ((MauiWinUIWindow)App.Current.Windows[0].Handler.PlatformView).WindowHandle;
            WinRT.Interop.InitializeWithWindow.Initialize(context, hwnd);

            var result = await context.RequestRateAndReviewAppAsync();
        });
#endif
```

3. Works without dispatcher (it appears it is not necessary)✅:
``` csharp 
#if WINDOWS
        var context = StoreContext.GetDefault();

        var hwnd = ((MauiWinUIWindow)App.Current.Windows[0].Handler.PlatformView).WindowHandle;
        WinRT.Interop.InitializeWithWindow.Initialize(context, hwnd);

        var result = await context.RequestRateAndReviewAppAsync();
#endif
```

![image](https://github.com/jamesmontemagno/StoreReviewPlugin/assets/7528322/2e7afd17-8c7e-46bd-8191-ce904acffba7)

The 6.1.1-beta package is probably still processing so I will try your latest comment with it when its ready.

**Comment by jamesmontemagno** [comment]
Perfect! yeah with my changes it should work as it is the same code you have basically :)

Thanks for checking this, i appreciate it.

**Comment by BurkusCat** [comment]
Unfortunately, trying out 6.1.1-beta with the following code:
``` csharp
#if WINDOWS
        var hwnd = ((MauiWinUIWindow)App.Current.Windows[0].Handler.PlatformView).WindowHandle;
        StoreReviewImplementation.WindowObject = hwnd;
        await storeReview.RequestReview(true);
#endif  
```

I get these exceptions:
```
Exception thrown: 'System.InvalidOperationException' in WinRT.Runtime.dll
Exception thrown: 'System.TypeInitializationException' in WinRT.Runtime.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in WinRT.Runtime.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in WinRT.Runtime.dll
```

![image](https://github.com/jamesmontemagno/StoreReviewPlugin/assets/7528322/65498fe1-8a84-4ebd-b939-d40838943905)

I've took a look at your branch it looks like what I actually need to be doing is passing the Window object:
``` csharp
#if WINDOWS
        var windowObject = (MauiWinUIWindow)App.Current.Windows[0].Handler.PlatformView;
        StoreReviewImplementation.WindowObject = windowObject;
        await storeReview.RequestReview(true);
#endif  
```

This works well 👍 Thank you for making these changes :)

**Comment by jamesmontemagno** [comment]
Oh perfect! Yeah i think having folks pass me the window will make the most sense. I think i will null it out after as well so it doesn't hang on to stuff.

I will change it to `Window`
