### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by Suplanus** [jamesmontemagno/StoreReviewPlugin#5]
## Feature Request:
Please support macOS 💕

**Comment by Suplanus** [comment]
I created the macOS support here: https://github.com/Suplanus/StoreReviewPlugin/tree/issue5

But I have some trouble with building it.
- The project I changed from `<Project Sdk="Microsoft.NET.Sdk">` to `<Project Sdk="MSBuild.Sdk.Extras/2.0.54">`.
- Removed other platforms (to test)
- Added code to the `StoreReviewImplementation.apple.cs` file

When I now build the app, I have this error, and don't know why:
![image](https://user-images.githubusercontent.com/2002916/82910273-ba598480-9f6a-11ea-8e58-f073b63935e3.png)

Perhaps you have time to look into it. If its fixed, I can test and make the PR.

**Comment by jamesmontemagno** [comment]
Added in 3.0
