### ISSUE TITLE
The managed type `Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListener` exists in multiple assemblies: Xamarin.Google.Android.Play.Core, Xamarin.Google.Android.Play.Core.Common

### ISSUE THREAD

**Issue by amahera** [jamesmontemagno/StoreReviewPlugin#52]
## Conflict with Xamarin.Google.Android.Play.Core.Common package
warning XA4214: The managed type `Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListener` exists in multiple assemblies: Xamarin.Google.Android.Play.Core, Xamarin.Google.Android.Play.Core.Common. Please refactor the managed type names in these assemblies so that they are not identical.
warning XA4214: References to the type `Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListener` will refer to `Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListener, Xamarin.Google.Android.Play.Core`.
warning XA4214: The managed type `Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListenerImplementor` exists in multiple assemblies: Xamarin.Google.Android.Play.Core, Xamarin.Google.Android.Play.Core.Common. Please refactor the managed type names in these assemblies so that they are not identical.
warning XA4214: References to the type `Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListenerImplementor` will refer to `Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListenerImplementor, Xamarin.Google.Android.Play.Core`.
warning XA4214: The managed type `Xamarin.Google.Android.Play.Core.Common.IIntentSenderForResultStarter` exists in multiple assemblies: Xamarin.Google.Android.Play.Core, Xamarin.Google.Android.Play.Core.Common. Please refactor the managed type names in these assemblies so that they are not identical.
warning XA4214: References to the type `Xamarin.Google.Android.Play.Core.Common.IIntentSenderForResultStarter` will refer to `Xamarin.Google.Android.Play.Core.Common.IIntentSenderForResultStarter, Xamarin.Google.Android.Play.Core`.
error XA4215: The Java type `com.google.android.play.core.listener.StateUpdatedListener` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
error XA4215:   `com.google.android.play.core.listener.StateUpdatedListener` generated by: Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListener, Xamarin.Google.Android.Play.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
error XA4215:   `com.google.android.play.core.listener.StateUpdatedListener` generated by: Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListener, Xamarin.Google.Android.Play.Core.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
error XA4215: The Java type `mono.com.google.android.play.core.listener.StateUpdatedListenerImplementor` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
error XA4215:   `mono.com.google.android.play.core.listener.StateUpdatedListenerImplementor` generated by: Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListenerImplementor, Xamarin.Google.Android.Play.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
error XA4215:   `mono.com.google.android.play.core.listener.StateUpdatedListenerImplementor` generated by: Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListenerImplementor, Xamarin.Google.Android.Play.Core.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
error XA4215: The Java type `com.google.android.play.core.common.IntentSenderForResultStarter` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
error XA4215:   `com.google.android.play.core.common.IntentSenderForResultStarter` generated by: Xamarin.Google.Android.Play.Core.Common.IIntentSenderForResultStarter, Xamarin.Google.Android.Play.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
error XA4215:   `com.google.android.play.core.common.IntentSenderForResultStarter` generated by: Xamarin.Google.Android.Play.Core.Common.IIntentSenderForResultStarter, Xamarin.Google.Android.Play.Core.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

## Version Number of Plugin: 
6.2.0

## Expected Behavior
- application build succesfully

## Actual Behavior
- build failed
## Steps to reproduce the Behavior
- Install Xamarin.Google.Android.Play.Integrity > 1.3.0.0
- Install Plugin.StoreReview
- verify that build fails

**Comment by jpacov** [comment]
Hi @amahera , you managed to get a workaround for this?

**Comment by amahera** [comment]
@jpacov in my case workaround was to use the older version of Xamarin.Firebase.Auth (122.2.0.1) which doesn't use Xamarin.Google.Android.Play.Integrity

**Comment by gwise-vision** [comment]
The problem with this is that it comes from a conflict between Xamarin.Google.Android.Play.App.Update and Xamarin.Google.Android.Play.Core used by Plugin.StoreReview.
You should remove Xamarin.Google.Android.Play.Core from Plugin.StoreReview and use Xamarin.Google.Android.Play.Review.

The solution is to remove Xamarin.Google.Android.Play.Core from Plugin.StoreReview and apply Xamarin.Google.Android.Play.Review.
Or, you can look at the StoreReview source and apply Xamarin.Google.Android.Play.Review directly to develop.

**Comment by jamesmontemagno** [comment]
Working on a new version now for this.

**Comment by jamesmontemagno** [comment]
Give https://www.nuget.org/packages/Plugin.StoreReview/7.0.0-beta a try

**Comment by amahera** [comment]
@jamesmontemagno , I tried beta version and got the same result
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: The Java type `com.google.android.play.core.listener.StateUpdatedListener` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215:   `com.google.android.play.core.listener.StateUpdatedListener` generated by: Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListener, Xamarin.Google.Android.Play.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215:   `com.google.android.play.core.listener.StateUpdatedListener` generated by: Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListener, Xamarin.Google.Android.Play.Core.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: The Java type `mono.com.google.android.play.core.listener.StateUpdatedListenerImplementor` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215:   `mono.com.google.android.play.core.listener.StateUpdatedListenerImplementor` generated by: Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListenerImplementor, Xamarin.Google.Android.Play.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215:   `mono.com.google.android.play.core.listener.StateUpdatedListenerImplementor` generated by: Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListenerImplementor, Xamarin.Google.Android.Play.Core.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: The Java type `com.google.android.play.core.common.IntentSenderForResultStarter` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215:   `com.google.android.play.core.common.IntentSenderForResultStarter` generated by: Xamarin.Google.Android.Play.Core.Common.IIntentSenderForResultStarter, Xamarin.Google.Android.Play.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215:   `com.google.android.play.core.common.IntentSenderForResultStarter` generated by: Xamarin.Google.Android.Play.Core.Common.IIntentSenderForResultStarter, Xamarin.Google.Android.Play.Core.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: The Java type `com.google.android.play.core.review.ReviewManager` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215:   `com.google.android.play.core.review.ReviewManager` generated by: Xamarin.Google.Android.Play.Core.Review.IReviewManager, Xamarin.Google.Android.Play.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215:   `com.google.android.play.core.review.ReviewManager` generated by: Xamarin.Google.Android.Play.Core.Review.IReviewManager, Xamarin.Google.Android.Play.Review, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: The Java type `com.google.android.play.core.review.model.ReviewErrorCode` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215:   `com.google.android.play.core.review.model.ReviewErrorCode` generated by: Xamarin.Google.Android.Play.Core.Review.Model.IReviewErrorCode, Xamarin.Google.Android.Play.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215:   `com.google.android.play.core.review.model.ReviewErrorCode` generated by: Xamarin.Google.Android.Play.Core.Review.Model.IReviewErrorCode, Xamarin.Google.Android.Play.Review, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

**Comment by gwise-vision** [comment]
> @jamesmontemagno , I tried beta version and got the same result C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: The Java type `com.google.android.play.core.listener.StateUpdatedListener` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted. C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: `com.google.android.play.core.listener.StateUpdatedListener` generated by: Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListener, Xamarin.Google.Android.Play.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: `com.google.android.play.core.listener.StateUpdatedListener` generated by: Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListener, Xamarin.Google.Android.Play.Core.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: The Java type `mono.com.google.android.play.core.listener.StateUpdatedListenerImplementor` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted. C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: `mono.com.google.android.play.core.listener.StateUpdatedListenerImplementor` generated by: Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListenerImplementor, Xamarin.Google.Android.Play.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: `mono.com.google.android.play.core.listener.StateUpdatedListenerImplementor` generated by: Xamarin.Google.Android.Play.Core.Listener.IStateUpdatedListenerImplementor, Xamarin.Google.Android.Play.Core.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: The Java type `com.google.android.play.core.common.IntentSenderForResultStarter` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted. C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: `com.google.android.play.core.common.IntentSenderForResultStarter` generated by: Xamarin.Google.Android.Play.Core.Common.IIntentSenderForResultStarter, Xamarin.Google.Android.Play.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: `com.google.android.play.core.common.IntentSenderForResultStarter` generated by: Xamarin.Google.Android.Play.Core.Common.IIntentSenderForResultStarter, Xamarin.Google.Android.Play.Core.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: The Java type `com.google.android.play.core.review.ReviewManager` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted. C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: `com.google.android.play.core.review.ReviewManager` generated by: Xamarin.Google.Android.Play.Core.Review.IReviewManager, Xamarin.Google.Android.Play.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: `com.google.android.play.core.review.ReviewManager` generated by: Xamarin.Google.Android.Play.Core.Review.IReviewManager, Xamarin.Google.Android.Play.Review, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: The Java type `com.google.android.play.core.review.model.ReviewErrorCode` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted. C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: `com.google.android.play.core.review.model.ReviewErrorCode` generated by: Xamarin.Google.Android.Play.Core.Review.Model.IReviewErrorCode, Xamarin.Google.Android.Play.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.145\tools\Xamarin.Android.Common.targets(1544,3): error XA4215: `com.google.android.play.core.review.model.ReviewErrorCode` generated by: Xamarin.Google.Android.Play.Core.Review.Model.IReviewErrorCode, Xamarin.Google.Android.Play.Review, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null



Removing Xamarin.Google.Android.Play.Core .....

**Comment by jamesmontemagno** [comment]
Yeah, you will have to remove the Play.Core as I have moved to Play.Review if you added it manually

**Comment by amahera** [comment]
@jamesmontemagno without Play.Core everything works fine, thank you
