### ISSUE TITLE
Review dialog quota

### ISSUE THREAD

**Issue by CostasAthan** [jamesmontemagno/StoreReviewPlugin#53]
Using the Plugin does not always open the dialog.

Most probably that [has to do with certain quotas](https://developer.android.com/guide/playcore/in-app-review#quotas):

> To provide a great user experience, Google Play enforces a time-bound quota on how often a user can be shown the review dialog. Because of this quota, calling the launchReviewFlow method more than once during a short period of time (for example, less than a month) might not always display a dialog.

Is there a way to detect when the review dialog fails to open in order to redirect the users to the Play Store in that case?

**Comment by jamesmontemagno** [comment]
There is not unfortunatelly from what I have seen
