### ISSUE TITLE
Xamarin.Google.Android.Play.Core -> Xamarin.Google.Android.Play.Review

### ISSUE THREAD

**Issue by gwise-vision** [jamesmontemagno/StoreReviewPlugin#54]
Hi, james

I use Xamarin.Google.Android.Play.App.Update to auto-update my App on Android.

However, when I use Plugin.StoreReview together, Xamarin.Google.Android.Play.App.Update and Xamarin.Google.Android.Play.Core conflict.

Removing Xamarin.Google.Android.Play.Core from Plugin.StoreReview and using Xamarin.Google.Android.Play.Review solves the problem.

**Comment by jamesmontemagno** [comment]
Will add this to my backlog. I am goign to target .net 8/9 on this library only and will make it easier to work

**Comment by jamesmontemagno** [comment]
Give https://www.nuget.org/packages/Plugin.StoreReview/7.0.0-beta a try

**Comment by pulmuone** [comment]
> Give https://www.nuget.org/packages/Plugin.StoreReview/7.0.0-beta a try

Ｔｈａｎｋ ｙｏｕ。
